platform:
- x64

image:
- Visual Studio 2017

install:
- cd scripts && call prepare_mkl.bat && cd ..

build_script:
- for /f "usebackq tokens=*" %%A in (`git rev-parse --short HEAD`) do set "MKLDNN_REV=%%A"
- echo %MKLDNN_REV%

- mkdir build-release
- cd build-release
- cmake -G "Visual Studio 14 Win64" -DCMAKE_INSTALL_PREFIX=c:\mkl-dnn-%MKLDNN_REV%-win64-release ..
- cmake --build . --config Release --target install
- mkdir c:\mkl-dnn-%MKLDNN_REV%-win64-release\share\doc\mklml\
- copy ..\external\mklml_win_2018.0.3.20180406\license.txt c:\mkl-dnn-%MKLDNN_REV%-win64-release\share\doc\mklml\
- cd ..

after_test:
- 7z a mkl-dnn-%MKLDNN_REV%-win64-release.7z c:\mkl-dnn-%MKLDNN_REV%-win64-release

artifacts:
- path: '*.7z'
