post_install() {
    which MSVCR120.dll
    if [ $? = 0 ]; then
        echo "MSVCR120.dll is found."
    else
        echo "!!! libmkldnn depends on MSVCR120.dll but it is not found.";
        echo "!!! MSVCR120.dll is contained in Microsoft Visual C++ 2013 Redistributable Packages.";
        echo "!!! Please download it from https://www.microsoft.com/en-us/download/details.aspx?id=40784"
        echo "!!! then install it.";
    fi
}
